// src/lib/utils/mockData.ts
import { Contact, NewsletterSubscriber, Quote, ActivityItem } from '@/types';

// ============================================
// MOCK CONTACTS
// ============================================
export const mockContacts: Contact[] = [
    {
        id: '1',
        name: 'John Kamau',
        email: 'john.kamau@example.com',
        phone: '+254 712 345 678',
        serviceType: 'wooden-house',
        location: 'Nairobi',
        budget: '500k-1m',
        timeline: '3-6months',
        message: 'I am interested in building a 2-bedroom wooden house in Nairobi. I have a plot ready and would like to know the total cost including installation.',
        status: 'new',
        priority: 'high',
        createdAt: new Date('2024-12-10'),
    },
    {
        id: '2',
        name: 'Mary Wanjiku',
        email: 'mary.w@example.com',
        phone: '+254 723 456 789',
        serviceType: 'carpentry',
        location: 'Kiambu',
        budget: 'under-500k',
        timeline: '1-3months',
        message: 'Need custom furniture for my office - desks, shelves, and cabinets. Can you provide a quotation?',
        status: 'contacted',
        priority: 'normal',
        notes: 'Called on 12/11. Scheduled site visit for 12/15.',
        createdAt: new Date('2024-12-08'),
        contactedAt: new Date('2024-12-11'),
    },
    {
        id: '3',
        name: 'Peter Omondi',
        email: 'peter.omondi@example.com',
        phone: '+254 734 567 890',
        serviceType: 'wooden-house',
        location: 'Naivasha',
        budget: '1m-2m',
        timeline: '6-12months',
        message: 'Planning to build a 3-bedroom wooden house near Lake Naivasha. Would like to see designs and get pricing.',
        status: 'quoted',
        priority: 'normal',
        notes: 'Sent quote QT-2024-001 on 12/09.',
        createdAt: new Date('2024-12-05'),
        contactedAt: new Date('2024-12-07'),
    },
    {
        id: '4',
        name: 'Grace Muthoni',
        email: 'grace.m@example.com',
        phone: '+254 745 678 901',
        serviceType: 'consultation',
        location: 'Nakuru',
        budget: 'flexible',
        timeline: 'planning',
        message: 'I have land in Nakuru and want to explore wooden house options. Looking for design consultation.',
        status: 'new',
        priority: 'low',
        createdAt: new Date('2024-12-12'),
    },
    {
        id: '5',
        name: 'David Kipchoge',
        email: 'david.k@example.com',
        phone: '+254 756 789 012',
        serviceType: 'wooden-house',
        location: 'Eldoret',
        budget: '2m-5m',
        timeline: 'urgent',
        message: 'Need a wooden house built ASAP. Have all permits ready. Looking for fastest timeline possible.',
        status: 'converted',
        priority: 'urgent',
        notes: 'Contract signed. Deposit received. Construction starts 12/20.',
        createdAt: new Date('2024-11-28'),
        contactedAt: new Date('2024-11-29'),
    },
    {
        id: '6',
        name: 'Sarah Njeri',
        email: 'sarah.njeri@example.com',
        phone: '+254 767 890 123',
        serviceType: 'wooden-house',
        location: 'Thika',
        budget: '500k-1m',
        timeline: '3-6months',
        message: 'Looking for a small wooden cabin for my garden. Size around 3m x 3m.',
        status: 'closed',
        priority: 'normal',
        notes: 'Customer decided to go with another contractor.',
        createdAt: new Date('2024-11-20'),
        contactedAt: new Date('2024-11-22'),
    },
    {
        id: '7',
        name: 'James Mwangi',
        email: 'james.mwangi@example.com',
        phone: '+254 778 901 234',
        serviceType: 'carpentry',
        location: 'Mombasa',
        budget: '1m-2m',
        timeline: '1-3months',
        message: 'Need wooden decking and outdoor furniture for a beach resort.',
        status: 'quoted',
        priority: 'high',
        notes: 'Sent detailed quote. Awaiting response.',
        createdAt: new Date('2024-12-06'),
        contactedAt: new Date('2024-12-08'),
    },
    {
        id: '8',
        name: 'Lucy Akinyi',
        email: 'lucy.a@example.com',
        phone: '+254 789 012 345',
        serviceType: 'wooden-house',
        location: 'Kisumu',
        budget: 'over-5m',
        timeline: '6-12months',
        message: 'Planning a luxury wooden home project. Need full consultation and custom design.',
        status: 'contacted',
        priority: 'high',
        notes: 'Scheduled video call for 12/14.',
        createdAt: new Date('2024-12-09'),
        contactedAt: new Date('2024-12-11'),
    },
];

// ============================================
// MOCK NEWSLETTER SUBSCRIBERS
// ============================================
export const mockNewsletter: NewsletterSubscriber[] = [
    {
        id: '1',
        email: 'john.kamau@example.com',
        name: 'John Kamau',
        status: 'active',
        source: 'contact-form',
        subscribedAt: new Date('2024-12-10'),
    },
    {
        id: '2',
        email: 'jane.doe@example.com',
        name: 'Jane Doe',
        status: 'active',
        source: 'website',
        subscribedAt: new Date('2024-12-08'),
    },
    {
        id: '3',
        email: 'robert.smith@example.com',
        status: 'active',
        source: 'website',
        subscribedAt: new Date('2024-12-05'),
    },
    {
        id: '4',
        email: 'alice.johnson@example.com',
        name: 'Alice Johnson',
        status: 'unsubscribed',
        source: 'manual',
        subscribedAt: new Date('2024-11-20'),
        unsubscribedAt: new Date('2024-12-01'),
    },
    {
        id: '5',
        email: 'michael.brown@example.com',
        name: 'Michael Brown',
        status: 'active',
        source: 'website',
        subscribedAt: new Date('2024-12-11'),
    },
];

// ============================================
// MOCK QUOTES (SUMMARY-ONLY, CLEAN)
// ============================================
export const mockQuotes: Quote[] = [
    {
        id: '1',
        quoteNumber: 'QT-2024-001',
        contactId: '3',
        customerName: 'Peter Omondi',
        customerEmail: 'peter.omondi@example.com',
        customerPhone: '+254 734 567 890',
        houseType: '3-bedroom',
        houseSize: '8m x 10m',
        location: 'Naivasha',
        basePrice: 800000,
        additionalCosts: [
            { id: '1', item: 'Electrical Wiring Preparation', cost: 50000 },
            { id: '2', item: 'Plumbing Preparation', cost: 60000 },
            { id: '3', item: 'Premium Varnish Finish', cost: 40000 },
        ],
        totalPrice: 950000,
        discount: 0,
        finalPrice: 950000,
        paymentTerms: '50% deposit, 50% on completion',
        deliveryTimeline: '3-4 weeks',
        validityPeriod: '30 days',
        status: 'sent',
        notes: 'Customer requested premium finish',
        createdAt: new Date('2024-12-09'),
        sentAt: new Date('2024-12-09'),
    },
    {
        id: '2',
        quoteNumber: 'QT-2024-002',
        contactId: '7',
        customerName: 'James Mwangi',
        customerEmail: 'james.mwangi@example.com',
        customerPhone: '+254 778 901 234',
        houseType: 'custom',
        location: 'Mombasa',
        basePrice: 1200000,
        additionalCosts: [
            { id: '1', item: 'Marine-grade Treatment', cost: 100000 },
            { id: '2', item: 'Outdoor Furniture Set', cost: 200000 },
        ],
        totalPrice: 1500000,
        discount: 50000,
        finalPrice: 1450000,
        paymentTerms: '30% deposit, 40% mid-project, 30% on completion',
        deliveryTimeline: '6-8 weeks',
        validityPeriod: '45 days',
        status: 'viewed',
        notes: 'Resort project - special coastal treatment required',
        createdAt: new Date('2024-12-08'),
        sentAt: new Date('2024-12-08'),
        viewedAt: new Date('2024-12-10'),
    },
    {
        id: '3',
        quoteNumber: 'QT-2024-003',
        contactId: '1',
        customerName: 'John Kamau',
        customerEmail: 'john.kamau@example.com',
        customerPhone: '+254 712 345 678',
        houseType: '2-bedroom',
        houseSize: '6m x 8m',
        location: 'Nairobi',
        basePrice: 500000,
        additionalCosts: [],
        totalPrice: 500000,
        discount: 0,
        finalPrice: 500000,
        paymentTerms: '50% deposit, 50% on completion',
        deliveryTimeline: '2-3 weeks',
        validityPeriod: '30 days',
        status: 'draft',
        notes: 'Pending customer confirmation on design',
        createdAt: new Date('2024-12-12'),
    },
];

// ============================================
// MOCK ACTIVITY FEED
// ============================================
export const mockActivity: ActivityItem[] = [
    {
        id: '1',
        type: 'contact',
        title: 'New contact submission',
        description: 'Grace Muthoni submitted a consultation request',
        timestamp: new Date('2024-12-12T14:30:00'),
    },
    {
        id: '2',
        type: 'status_change',
        title: 'Contact status updated',
        description: 'Mary Wanjiku marked as "Contacted"',
        timestamp: new Date('2024-12-11T11:15:00'),
    },
    {
        id: '3',
        type: 'newsletter',
        title: 'New newsletter subscriber',
        description: 'Michael Brown subscribed to newsletter',
        timestamp: new Date('2024-12-11T09:45:00'),
    },
    {
        id: '4',
        type: 'contact',
        title: 'New contact submission',
        description: 'John Kamau submitted a wooden house inquiry',
        timestamp: new Date('2024-12-10T16:20:00'),
    },
    {
        id: '5',
        type: 'quote',
        title: 'Quote sent',
        description: 'Quote QT-2024-001 sent to Peter Omondi',
        timestamp: new Date('2024-12-09T13:00:00'),
    },
    {
        id: '6',
        type: 'quote',
        title: 'Quote viewed',
        description: 'James Mwangi viewed quote QT-2024-002',
        timestamp: new Date('2024-12-10T10:30:00'),
    },
    {
        id: '7',
        type: 'contact',
        title: 'New contact submission',
        description: 'Lucy Akinyi submitted a luxury home inquiry',
        timestamp: new Date('2024-12-09T08:15:00'),
    },
    {
        id: '8',
        type: 'status_change',
        title: 'Contact converted',
        description: 'David Kipchoge contract signed - Converted!',
        timestamp: new Date('2024-11-29T15:45:00'),
    },
];